MicrosoftAppId=f3eb38b6-6a3e-4ccb-b4ff-d01a6d4086b7
MicrosoftAppPassword=kZT8Q~nanc9x5gI7YLKYk6b64D.tV4ptJMIAaaAO
MicrosoftAppTenantId=099457d3-3ee6-4582-ab1f-84ea1c09b9ad
# Force authentication to use your specific tenant
MicrosoftAppType=SingleTenant
# Explicitly set the authority host with your tenant ID
AuthorityHostUrl=https://login.microsoftonline.com/099457d3-3ee6-4582-ab1f-84ea1c09b9ad
server.port=3978
