# Bot Framework Configuration
MicrosoftAppId=f3eb38b6-6a3e-4ccb-b4ff-d01a6d4086b7
MicrosoftAppPassword=kZT8Q~nanc9x5gI7YLKYk6b64D.tV4ptJMIAaaAO
MicrosoftAppTenantId=099457d3-3ee6-4582-ab1f-84ea1c09b9ad
MicrosoftAppType=MultiTenant

# Server Configuration
server.port=3978

# Authentication Configuration
AuthorityHostUrl=https://login.microsoftonline.com/common
ToChannelFromBotLoginUrl=https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token
ToChannelFromBotOAuthScope=https://api.botframework.com/.default

# Graceful Shutdown Configuration
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
